
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-boot-library
    description: A simple library project.
    author: Sergii Bezrukov
    version: '@project.version@'
spring:
  profiles:
    active: dev